#!/usr/bin/env bash
# Install configring it with bash script

sudo apt-get updte
sudo apt-get install -y haproxy

sudo echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo cat <<EOT | sudo tee -a /etc/haproxy/haproxy.cfg
frontend georrgeem178.tech
    timeout client  30000
    bind 0:80
    default_backend georrgeem178.tech_backend

backend georrgeem178.tech_backend
    timeout connect  3000
    timeout server  30000
    balance roundrobin
    server 492020-web-01 54.86.222.127:80 check
    server 492020-web-02 3.80.19.217:80 check
EOT

sudo service haproxy restart